# Spring Boot Application Configuration
spring.application.name=System Monitor API
server.port=8000
server.servlet.context-path=/api

# Logging
logging.level.root=INFO
logging.level.com.geez14.sysmon=DEBUG

# Jackson Configuration
spring.jackson.serialization.indent-output=true
spring.jackson.default-property-inclusion=non_null
